# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'MAINTAINERS'
      - 'NOTICE'
      - 'art/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: lint-${{ matrix.runtime }}
    strategy:
      matrix:
        runtime: ["common", "wasmtime", "wasmedge", "wasmer"]
    uses: ./.github/workflows/action-check.yml
    with:
      os: ubuntu-latest
      runtime: ${{ matrix.runtime }}

  build-ubuntu:
    name: test-${{ matrix.runtime }}-${{ matrix.libc }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        runtime: ["wasmtime", "wasmedge", "wasmer"]
        libc: ["gnu", "musl"]
    uses: ./.github/workflows/action-build.yml
    with:
      os: ubuntu-22.04
      runtime: ${{ matrix.runtime }}
      target: "x86_64-unknown-linux-${{ matrix.libc }}"
      slug: "x86_64-linux-${{ matrix.libc }}"
      arch: x86_64
